### ISSUE TITLE
Line 24 'Attribute Missing' After Calling nix-shell

### ISSUE THREAD

**Issue by Davidhw** [nix-community/pip2nix#31]
Hi, I am attempting to use pip2nix and a requirements.txt file to create python-packages.nix and default.nix files that will allow me to install my python requirements using nix. I am encountering an 'Attribute Missing' error. Do you know what I am doing wrong? Thanks!

Replication Steps:

```
git clone https://github.com/Davidhw/infocatch.git
cd infocatch
pip2nix generate -r requirements.txt
pip2nix scaffold --package infocatch
nix-shell --show-trace
```

Output:

> error: while evaluating anonymous function at /home/d/dev/infocatch/default.nix:1:1, called from undefined position:
> while evaluating the attribute ‘infocatch’ at /home/d/dev/infocatch/default.nix:24:5:
> attribute ‘infocatch’ missing, at /home/d/dev/infocatch/default.nix:24:17

Failing Line:

```
    localOverrides = pythonPackages: {
    infocatch = pythonPackages.infocatch.override (attrs: {
      src = infocatch-src;
    });
  };

```

Content of default.nix:

```
{ pkgs ? (import <nixpkgs> {}), pythonPackages ? "python27Packages" }:
let
  basePythonPackages = with builtins; if isAttrs pythonPackages
    then pythonPackages
    else getAttr pythonPackages pkgs;

  elem = builtins.elem;
  basename = path: with pkgs.lib; last (splitString "/" path);
  startsWith = prefix: full: let
    actualPrefix = builtins.substring 0 (builtins.stringLength prefix) full;
  in actualPrefix == prefix;

  src-filter = path: type: with pkgs.lib;
    let
      ext = last (splitString "." path);
    in
      !elem (basename path) [".git" "__pycache__" ".eggs"] &&
      !elem ext ["egg-info" "pyc"] &&
      !startsWith "result" path;

  infocatch-src = builtins.filterSource src-filter ./.;

    localOverrides = pythonPackages: {
    infocatch = pythonPackages.infocatch.override (attrs: {
      src = infocatch-src;
    });
  };

  pythonPackagesWithLocals = basePythonPackages.override (a: {
    self = pythonPackagesWithLocals;
  })
  // (scopedImport {
    self = pythonPackagesWithLocals;
    super = basePythonPackages;
    inherit pkgs;
    inherit (pkgs) fetchurl fetchgit;
  } ./python-packages.nix);

  myPythonPackages =
    pythonPackagesWithLocals
    // (localOverrides pythonPackagesWithLocals);
in myPythonPackages.infocatch

```

**Comment by ktosiek** [comment]
The scaffold assumes your package is included in the generated python-packages.nix.
Can you try running `pip2nix generate -r requirements.txt .`, so your package is also included? (assuming your package does have it's own setup.py)

**Comment by Davidhw** [comment]
Thanks! The solution was indeed to create a setup.py file and run
`pip2nix generate -r requirements.txt .`

`For others' convenience, here's the [setup.py documentation](https://the-hitchhikers-guide-to-packaging.readthedocs.io/en/latest/creation.html#setup-py-description). Ensure you specify the install_requires field.
