### ISSUE TITLE
Moving to nix-community, changing maintainer

### ISSUE THREAD

**Issue by datakurre** [nix-community/pip2nix#51]
FWIW, I have forked this project to https://github.com/nix-community/pip2nix, added my patches for the latest nixpkgs, and intending to maintain it there. A couple of years ago I had more luck with pip2nix than pypi2nix (back then it had hard dependency on PyPI) so, I invested into pip2nix and I am still very happy with it.

@ktosiek I have not been able to contact @johbo about the maintenance of this repository, so would you be able to add me to the maintainers of https://pypi.org/project/pip2nix/ so that I could also make a new release.

**Comment by datakurre** [comment]
@johbo @ktosiek My offer for taking maintainership for pip2nix at PyPI is still open :pray:

**Comment by marcinkuzminski** [comment]
Bumping this too! I'll try to contact @johbo via other channels to check this.

**Comment by johbo** [comment]
It worked, thanks for pushing @marcinkuzminski ;)

@datakurre Awesome that you like it and are willing to take over maintaining it.

**Comment by johbo** [comment]
Updated the configuration in PyPI, hope it works now, so that you can already release via that path. I've added you as owner since you are willing to maintain it and I currently not actively using it.

**Comment by johbo** [comment]
In case you are keen to move the repository itself for any reason, please just ping me. @ktosiek back then did transfer his repository to me, so that issues etc. were preserved.

**Comment by datakurre** [comment]
@johbo Awesome! Thank you! I moved my fork at nix-community out of the way, so now it should be possible to

1) give me rights for the repository
2) add [maintainer=@datakurre] at the end of the description
3) transfer ownership of the repository to nix-community

https://nix-community.com/
https://github.com/nix-community

I am using this at work for a lot so I should have good changes to maintain. Hardest thing so far has been to understand all the features :)

**Comment by datakurre** [comment]
My fork is now at https://github.com/nix-community/pip2nix-fork

Once the original repository has been moved, I'll update it with my changes and branches and delete the fork.

**Comment by johbo** [comment]
Added you as collaborator. 

I was not able to trigger the transfer, might be that you can do this now. The error message I got is the following:

> nix-community already has a repository in the johbo/pip2nix network and You don’t have the permission to create public repositories on nix-community

**Comment by datakurre** [comment]
@johbo Unfortunately, I still don't see "Settings" tab on the repository.

But I managed to move my fork out of nix-community. Would you, please, be able to try one more time?

**Comment by datakurre** [comment]
@johbo As mentioned elsewhere, you should now have permissions to transfer this repository to nix-community and also the blocking repository has been moved. 👍

**Comment by datakurre** [comment]
> In case you are keen to move the repository itself for any reason, please just ping me.

@johbo Ping. I'm still keen to have this repository moved below nix-community. I assume all roadblocks have now been cleared.

**Comment by datakurre** [comment]
> In case you are keen to move the repository itself for any reason, please just ping me. @ktosiek back then did transfer his repository to me, so that issues etc. were preserved.

@johbo Ping. I'm still keen to have this repository moved below nix-community. I assume all roadblocks have now been cleared.

**Comment by johbo** [comment]
Hey, thanks for the ping, I've got stuck still with permission issues :(

<img width="571" alt="Screenshot 2020-05-25 at 08 52 37" src="https://user-images.githubusercontent.com/117805/82786573-2b167900-9e65-11ea-9848-101549d0e2bf.png">

**Comment by datakurre** [comment]
@johbo Could you please try one more time 😭 It seems that last time you were supposed to get invitation and join the organization for permissions.

https://github.com/nix-community/nix-community.org/issues/4#issuecomment-633576770

**Comment by johbo** [comment]
Odd, maybe the join failed back then. It's not transferred 🎉

**Comment by datakurre** [comment]
@johbo Thanks. Now you are free at last! :heart:
