### ISSUE TITLE
TypeError on 20.09 branch

### ISSUE THREAD

**Issue by zetashift** [nix-community/pip2nix#64]
So I'm new to Nix, sorry if I'm doing anything wrong but I could only install pip2nix using the 20.09 branch and running `pip2nix generate-r requirements.txt` in my project got me the following error:

```
Collecting greenlet!=0.4.17; python_version >= "3"
  Downloading greenlet-1.0.0-cp38-cp38-manylinux2010_x86_64.whl (165 kB)
     |████████████████████████████████| 165 kB 9.1 MB/s 
ERROR: Exception:
Traceback (most recent call last):
  File "/nix/store/15lagkiwbbadbkg4qlwac7r8yi25j016-python3.8-pip-20.1.1/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
    status = self.run(options, args)
  File "/home/rishi/dev/python/pip2nix/pip2nix/generate.py", line 343, in run
    return requirement_set
  File "/nix/store/q41k9x4wnh7g17adsir90bfzx6fy3smy-python3.8-contexter-0.1.4/lib/python3.8/site-packages/contexter.py", line 96, in __exit__
    reraise(exc)
  File "/nix/store/q41k9x4wnh7g17adsir90bfzx6fy3smy-python3.8-contexter-0.1.4/lib/python3.8/site-packages/contexter.py", line 26, in reraise
    raise exc[1].with_traceback(exc[2])
  File "/home/rishi/dev/python/pip2nix/pip2nix/generate.py", line 342, in run
    requirement_set = self.super_run(options, args)
  File "/home/rishi/dev/python/pip2nix/pip2nix/generate.py", line 321, in super_run
    self.process_requirements(
  File "/home/rishi/dev/python/pip2nix/pip2nix/generate.py", line 133, in process_requirements
    packages[req.name] = PythonPackage.from_requirements(
  File "/home/rishi/dev/python/pip2nix/pip2nix/models/package.py", line 126, in from_requirements
    toml_path = os.path.join(req.source_dir, 'pyproject.toml')
  File "/nix/store/0l519s624pxkpjjgw4hf146n4983fwza-python3-3.8.5/lib/python3.8/posixpath.py", line 76, in join
    a = os.fspath(a)
```

This is the repo I want to Nix-ify: https://github.com/kyclark/biofx_python/blob/main/requirements.txt

**Comment by datakurre** [comment]
@zetashift I'll check that.

**Comment by datakurre** [comment]
@zetashift Thanks. I had seen the issue before, but only now was able to resolve. I was no able to create python-packages.nix for that requirements.txt.

Yet, that looks like a hard one to build.

**Comment by zetashift** [comment]
> @zetashift Thanks. I had seen the issue before, but only now was able to resolve. I was no able to create python-packages.nix for that requirements.txt.

Thanks, `generate` works now!

> Yet, that looks like a hard one to build.

Well, experimenting is part of the fun. I hope it won't be impossible.

**Comment by datakurre** [comment]
@zetashift If it gets too complex, here's probably a working one:

https://gist.github.com/datakurre/614d6f9ee48c83bec101cd6b8cf0dbce

That relies on my "setup.nix"-approach I have been using for years now. It merges "python-packages.nix" with build recipes in the used nixpkgs. Sometimes it requires resolving naming differences, patching nicpkgs recipes for newer versions and simply adding some implicit dependencies into requirements.txt to allwo "setup.nix magic" resolve conflicting versions.

This particular requirements.txt become a good example requiring all of the usual tricks :see_no_evil:

**Comment by zetashift** [comment]
I was just about to ask if my current `shell.nix` is okay, haha! 

```nix
{ pkgs ? import <nixpkgs> {} }:

with pkgs;

let
  packageOverrides = pkgs.callPackage ./python-packages.nix {  };
  python = pkgs.python39.override { inherit packageOverrides; };

in mkShell {
  buildInputs = [ python ];
}
```

But comparing to your `setup.nix` I see that a lot still had to be done, woah.

**Comment by zetashift** [comment]
Trying to run your `setup.nix` I get: `error: nix-shell requires a single derivation` but googling this get's me mostly some stale issues?

**Comment by datakurre** [comment]
nix-shell setup.nix -A shell

nix-build setup.nix -A env

**Comment by zetashift** [comment]
Ah damn that makes sense :P, thanks a lot for your time!

**Comment by datakurre** [comment]
In principle, my setup.nix is generic helper that I copy paste around in projects. I should make it a scaffold for pip2nix, but have not managed yet. Usually I just need to customize aliases and overrides. Like this time these:

```
 # Alias packages with different names in requirements and in nixpkgs
  aliases = {
    "bottleneck" = "Bottleneck";
    "sqlalchemy" = "SQLAlchemy";
    "typing-extensions" = "typing_extensions";
    "setuptools-scm" = "setuptools_scm";
  };

  # Final overrides to fix issues all the magic above cannot fix automatically
  overrides = self: super: {
    "cryptography" = super."cryptography".overridePythonAttrs(old: {
      doCheck = false;
    });
    "PyICU" = super."PyICU".overridePythonAttrs(old: {
      patches = [];
    });
    "sphinx" = super."sphinx".overridePythonAttrs(old: {
      propagatedBuildInputs = old.propagatedBuildInputs ++ [ self.packaging ];
    });
    "new-py" = super."new-py".overridePythonAttrs(old: {
      postInstall = ''
        rm $out/${self.python.sitePackages}/__init__.py
        rm $out/${self.python.sitePackages}/__pycache__/__init__.cpython-38.pyc
      '';
    });
  };

**Comment by zetashift** [comment]
As a beginner, the `setup.nix` is a tough read, but I learned some really nifty things from it!
I don't know if it's Nix or Python but I do find the error messages a bit overwhelming and don't really know what to do with it or where to start solving it:
running `nix-shell setup.nix -A shell`

```
building
Executing setuptoolsBuildPhase
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff6b20d90>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools-scm/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5f93f10>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools-scm/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff6b0e520>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools-scm/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff6b0e490>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools-scm/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff6b0e430>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools-scm/
ERROR: Could not find a version that satisfies the requirement setuptools_scm<6.0,>=3.3.1 (from versions: none)
ERROR: No matching distribution found for setuptools_scm<6.0,>=3.3.1
Traceback (most recent call last):
  File "/nix/store/vliz92p6b5ykk3xqyd8rr6kiv50flfnd-python3.8-setuptools-47.3.1/lib/python3.8/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
    subprocess.check_call(cmd)
  File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/bin/python3.8', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/build/tmp7hk1e9fo', '--quiet', 'setuptools_scm<6.0,>=3.3.1']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 65, in <module>
    setup(
  File "/nix/store/vliz92p6b5ykk3xqyd8rr6kiv50flfnd-python3.8-setuptools-47.3.1/lib/python3.8/site-packages/setuptools/__init__.py", line 160, in setup
    _install_setup_requires(attrs)
  File "/nix/store/vliz92p6b5ykk3xqyd8rr6kiv50flfnd-python3.8-setuptools-47.3.1/lib/python3.8/site-packages/setuptools/__init__.py", line 155, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/nix/store/vliz92p6b5ykk3xqyd8rr6kiv50flfnd-python3.8-setuptools-47.3.1/lib/python3.8/site-packages/setuptools/dist.py", line 695, in fetch_build_eggs
    resolved_dists = pkg_resources.working_set.resolve(
  File "/nix/store/vliz92p6b5ykk3xqyd8rr6kiv50flfnd-python3.8-setuptools-47.3.1/lib/python3.8/site-packages/pkg_resources/__init__.py", line 780, in resolve
    dist = best[req.key] = env.best_match(
  File "/nix/store/vliz92p6b5ykk3xqyd8rr6kiv50flfnd-python3.8-setuptools-47.3.1/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/nix/store/vliz92p6b5ykk3xqyd8rr6kiv50flfnd-python3.8-setuptools-47.3.1/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/nix/store/vliz92p6b5ykk3xqyd8rr6kiv50flfnd-python3.8-setuptools-47.3.1/lib/python3.8/site-packages/setuptools/dist.py", line 754, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "/nix/store/vliz92p6b5ykk3xqyd8rr6kiv50flfnd-python3.8-setuptools-47.3.1/lib/python3.8/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
    raise DistutilsError(str(e))
distutils.errors.DistutilsError: Command '['/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/bin/python3.8', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/build/tmp7hk1e9fo', '--quiet', 'setuptools_scm<6.0,>=3.3.1']' returned non-zero exit status 1.
builder for '/nix/store/cnmmzh7r1xg9p9dg043z3wdmlsgsx5mv-python3.8-lazy-object-proxy-1.6.0.drv' failed with exit code 1
cannot build derivation '/nix/store/4c5wjnkmbfzyg3kfirkzvyyzkd31gk7p-python3-3.8.5-env.drv': 1 dependencies couldn't be built
error: build of '/nix/store/4c5wjnkmbfzyg3kfirkzvyyzkd31gk7p-python3-3.8.5-env.drv' failed
```

**Comment by zetashift** [comment]
Nevermind I had to re-generate `requirements.txt` my bad, damn.

**Comment by datakurre** [comment]
Do you mean that nix-shell setup.nix -A shell with my gist did not work? I’m checking, because it should have had everything pinned to exact version and be reproducible.

I need to try it on other machine also...

**Comment by zetashift** [comment]
> Do you mean that nix-shell setup.nix -A shell with my gist did not work? I’m checking, because it should have had everything pinned to exact version and be reproducible. I need to try it on other machine also...

Yea, but it didn't work because I had a wrong `requirements.txt` and thus a wrong `python-packages.nix`.

From what I can see it's currently building numpy(and all the other packages), so far so good!

**Comment by datakurre** [comment]
Yes, those change were side effect from using my setup.nix. Because when it merges pip2nix-generated python-packages with nixpkgthinkings python-packages, nixpkgs build instructions may include some surprise dependencies, which conflict with the versions generated with pip2nix (without considering about nixpkgs ones). Including those into requirements.txt make pip2nix include compatible versions in python-packages.nix, causing setup.nix to replace nixpkgs versions with those and then build might work.

May I ask, who did you find pip2nix? It is not the newest and fanciest Python requirements generator for Nix, and usually not even listed in such listings. That said, I intent to keep using and maintaining it, because so far it has been easier than rewrite hundred-someting projects to use something else... The main downside in pip2nix is that because it depends on pip internal api, which pip keeps iterating on every release, also pip2nix needs changes for every NixOS release (with new pip version). [Yet, if I have not yet fixed pip2nix, often it is also possible to build python-packages.nix on older nixpkgs and then use that on a newer one.]

**Comment by zetashift** [comment]
Ah I see, the `setup.nix` kinda makes that clear too. At the surface it looks really complicated, but reading into it, it's makes some very logical steps.

I found pip2nix by reading Nix's Python language section in the docs, there it had a reference to `pip2nix`: https://nixos.wiki/wiki/Python and in your README I saw exactly was I was looking for. I also looked at mach-nix, but I am currently still building all the libraries, so I haven't had time to try that out. Not sure if that would make things easier. But even if it's not fancy(I'm not looking for anything fancy either), I'm currently just playing around with Nix and Python and hope to learn a thing or two, and I learned a lot already from your `setup.nix` :D

**Comment by zetashift** [comment]
Well running into another hiccup

```
CPU dispatch  : 
  Requested   : 'max -xop -fma4'
  Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_KNL AVX512_KNM AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
  Generated   : none
CCompilerOpt._cache_write[796] : write cache to path -> /build/scipy-1.5.2/build/temp.linux-x86_64-3.8/ccompiler_opt_cache_clib.py
builder for '/nix/store/6jfv5x8kq2x6ir5m83ng7kwq9c4ps4ds-python3.8-scipy-1.5.2.drv' failed with exit code 1
cannot build derivation '/nix/store/2l237df5asqy47c3l4wcy6jq32zn2yi0-python3-3.8.5-env.drv': 1 dependencies couldn't be built
error: build of '/nix/store/2l237df5asqy47c3l4wcy6jq32zn2yi0-python3-3.8.5-env.drv' failed
```

So I can't build scipy and that's why it's failing?

**Comment by datakurre** [comment]
@zetashift That's unfortunate :(

I don't know details on scipy, but it could be possible to override the inherited nixpkgs derivation and alter its build configuration https://github.com/NixOS/nixpkgs/blob/20.09/pkgs/development/python-modules/scipy/default.nix

Alternatively, if you have an another machine that could build it, you should be able to get a personal cachix.org binary cache and use that to cache successful build from the other machine.

For the latter approach, you could try if you can use the build from my cache:

1) enable by cachix cache by following instructions at https://app.cachix.org/cache/datakurre

2) clone my gist to ensure exact nix functions

        git clone git@gist.github.com:614d6f9ee48c83bec101cd6b8cf0dbce

3) try building it again, hopefully it could now download the prebuild versions from the cache

**Comment by zetashift** [comment]
It works!
![image](https://user-images.githubusercontent.com/1857826/115448063-8558bf00-a219-11eb-8fd1-d071e992712a.png)

I can't thank you enough, using your cachix I was done in less than 2 minutes :D. Weird that it didn't want to compile for me and to be honest altering build configurations sounded like a really daunting task for a Nix beginner.

**Comment by zetashift** [comment]
Very last (and minor) question, since everything just works now, since I'm using lorri: https://github.com/target/lorri , I'd like to have `nix-shell setup.nix -A shell` functionality in a `shell.nix`, I don't know enough Nix, but is there a way to "call" the this https://gist.github.com/datakurre/614d6f9ee48c83bec101cd6b8cf0dbce#file-setup-nix-L140 function in a way?

**Comment by datakurre** [comment]
@zetashift Wow, there's always something new. I'm using niv and direnv, but lorri is a new one for me.

I pushed new version of the gist with example shell.nix. It would also be possible to pass custom nixpkgs version to setup.nix, but it would cause rebuild

```nix
pkgs.mkShell {
  buildInputs = [
    (import ./setup.nix { inherit pkgs; }).python
  ];
}
```

Please note that I did also do small change to the end of setup.nix to expose "python" with all the packages in requirements.txt.

**Comment by datakurre** [comment]
@zetashift One more magic oneliner. Think this as `pip freeze`. Credits for this one goes to my co-worker @zemm

    grep "pname =\|version =" python-packages.nix|awk "ORS=NR%2?FS:RS"|sed 's|.*"\(.*\)";.*version = "\(.*\)".*|\1==\2|'

**Comment by zetashift** [comment]
Woah it's working brilliantly now! I learned a lot too. No more questions from me :P, thanks for your time.

EDIT: and your coworker for the oneliner, I specified them now all in my requirements.txt!

**Comment by zemm** [comment]
@zetashift TBH that has a nasty assumption of the order of the two fields, and it could probably be done better for example solely in Awk. I should learn it some day... Well, hopefully, if it ever breaks, it should be obvious.

For the fun of it, I tried to golf it solely with sed, but as [the manual](https://www.gnu.org/software/sed/manual/html_node/Programming-Commands.html#Programming-Commands) says on advanced commands

> In most cases, use of these commands indicates that you are probably better off programming in something like awk or Perl.

so I won't be posting that :)

**Comment by zetashift** [comment]
> @zetashift TBH that has a nasty assumption of the order of the two fields, and it could probably be done better for example solely in Awk. I should learn it some day... Well, hopefully, if it ever breaks, it should be obvious.
> 
Well (for now) it worked fine for me, thank you :100: 

> For the fun of it, I tried to golf it solely with sed, but as the manual says on advanced commands

Coincedentally I am trying to learn sed/awk as better tools for working with the command line, very cool stuff nonetheless.
