### ISSUE TITLE
importlib.metadata.PackageNotFoundError: pip2nix

### ISSUE THREAD

**Issue by milahu** [nix-community/pip2nix#72]
... when i call `nix-shell release.nix -A pip2nix.python39`

works with `nix-shell release.nix -A pip2nix.python36`

**Comment by datakurre** [comment]
@milahu Should just `nix-shell release.nix -A pip2nix.python39` cause the error? I cannot reproduce with just that. Could it be that you have existing PYTHONPATH set that affects the call?

**Comment by milahu** [comment]
yes! `PYTHONPATH` was the problem. i used `pip` to test-install some packages ...

most brutal solution: `rm -rf ~/.local/lib/python*`
